Partial Class FRMHHSTORICO
  Inherits FRM__CHIL
  Friend WithEvents grvStorico As NTSInformatica.NTSGridView
  Friend WithEvents grStorico As NTSInformatica.NTSGrid
  Friend WithEvents NtsPanel1 As NTSInformatica.NTSPanel
  Friend WithEvents mo_riga As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_codart As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_descr As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_unmis As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_colli As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_colpre As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_coleva As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_ump As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_quant As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_quapre As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_quaeva As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_flevapre As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_flevas As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_prezzo As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_scont1 As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_scont2 As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_datcons As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_confermato As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_rilasciato As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_aperto As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_ricimp As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_provv As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_provv2 As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_controp As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_codiva As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_stasino As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_codcfam As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_commeca As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_subcommeca As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_codcena As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_note As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_valore As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_datconsor As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_codclie As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_perqta As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_valoremm As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_flkit As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_ktriga As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_oatipo As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_oaanno As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_oaserie As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_oanum As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_oariga As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_oasalcon As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_pmtaskid As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_pmqtadis As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_pmvaldis As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_matric As NTSInformatica.NTSGridColumn
public WithEvents PnCPNEPnMain As NTSInformatica.NTSPanel
End Class
