Partial Class FrmRicerca
  Inherits FRM__CHIL
  Friend WithEvents NtsPanelFiltri As NTSInformatica.NTSPanel
  Friend WithEvents NtsLabel1 As NTSInformatica.NTSLabel
  Friend WithEvents NtsPanelFiltriSx As NTSInformatica.NTSPanel
  Friend WithEvents NtsLabel6 As NTSInformatica.NTSLabel
  Friend WithEvents edxx_CommessaA As NTSInformatica.NTSTextBoxNum
  Friend WithEvents edxx_NumdocA As NTSInformatica.NTSTextBoxNum
  Friend WithEvents edxx_CommessaDa As NTSInformatica.NTSTextBoxNum
  Friend WithEvents edxx_NumdocDa As NTSInformatica.NTSTextBoxNum
  Friend WithEvents Edxx_AnnoA As NTSInformatica.NTSTextBoxNum
  Friend WithEvents NtsLabel5 As NTSInformatica.NTSLabel
  Friend WithEvents NtsLabel4 As NTSInformatica.NTSLabel
  Friend WithEvents NtsLabel3 As NTSInformatica.NTSLabel
  Friend WithEvents NtsLabel2 As NTSInformatica.NTSLabel
  Friend WithEvents Edxx_AnnoDa As NTSInformatica.NTSTextBoxNum
  Friend WithEvents lbFiltriSxDa As NTSInformatica.NTSLabel
  Friend WithEvents NtsPanelFiltriDx As NTSInformatica.NTSPanel
  Friend WithEvents Edxx_CodAgenA As NTSInformatica.NTSTextBoxNum
  Friend WithEvents Edxx_CodAgenDa As NTSInformatica.NTSTextBoxNum
  Friend WithEvents NtsLabel7 As NTSInformatica.NTSLabel
  Friend WithEvents Edxx_AgenziaA As NTSInformatica.NTSTextBoxNum
  Friend WithEvents Edxx_AgenziaDa As NTSInformatica.NTSTextBoxNum
  Friend WithEvents edxx_ContoA As NTSInformatica.NTSTextBoxNum
  Friend WithEvents NtsLabel8 As NTSInformatica.NTSLabel
  Friend WithEvents NtsLabel9 As NTSInformatica.NTSLabel
  Friend WithEvents NtsLabel10 As NTSInformatica.NTSLabel
  Friend WithEvents NtsLabel11 As NTSInformatica.NTSLabel
  Friend WithEvents edxx_ContoDa As NTSInformatica.NTSTextBoxNum
  Friend WithEvents NtsLabel12 As NTSInformatica.NTSLabel
  Friend WithEvents Cbxx_Tipo As NTSInformatica.NTSComboBox
  Friend WithEvents NtsPanelForm As NTSInformatica.NTSPanel
  Friend WithEvents Edxx_SerieA As NTSInformatica.NTSTextBoxStr
  Friend WithEvents Edxx_SerieDa As NTSInformatica.NTSTextBoxStr
  Friend WithEvents NtsPanelGriglia As NTSInformatica.NTSPanel
  Friend WithEvents grRigheOrdPre As NTSInformatica.NTSGrid
  Friend WithEvents grvRigheOrdPre As NTSInformatica.NTSGridView
  Friend WithEvents td_tipork As NTSInformatica.NTSGridColumn
  Friend WithEvents td_anno As NTSInformatica.NTSGridColumn
  Friend WithEvents td_serie As NTSInformatica.NTSGridColumn
  Friend WithEvents td_numord As NTSInformatica.NTSGridColumn
  Friend WithEvents td_datord As NTSInformatica.NTSGridColumn
  Friend WithEvents an_descr1 As NTSInformatica.NTSGridColumn
  Friend WithEvents an_conto As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_commeca As NTSInformatica.NTSGridColumn
  Friend WithEvents td_codagen As NTSInformatica.NTSGridColumn
  Friend WithEvents xx_agente As NTSInformatica.NTSGridColumn
  Friend WithEvents td_codagen2 As NTSInformatica.NTSGridColumn
  Friend WithEvents xx_agenzia As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_note As NTSInformatica.NTSGridColumn
  Friend WithEvents mo_descr As NTSInformatica.NTSGridColumn
  Friend WithEvents cmdSeleziona As NTSInformatica.NTSButton
  Friend WithEvents cmdAnnulla As NTSInformatica.NTSButton
  Friend WithEvents cmdRicerca As NTSInformatica.NTSButton
  Friend WithEvents xx_sel As NTSInformatica.NTSGridColumn
  Friend WithEvents td_tipobf As NTSInformatica.NTSGridColumn
  Friend WithEvents cmdCPNEDuplica As NTSInformatica.NTSButton
public WithEvents PnCPNEPnMain As NTSInformatica.NTSPanel
    Friend WithEvents edxx_descrtitolo As NTSTextBoxStr
    Friend WithEvents NtsLabel13 As NTSLabel
End Class
